name: ci-cd-fresh-react-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-cd-fresh-react-app-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Check for package-lock.json
        id: check_lockfile
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo "lockfile=true" >> $GITHUB_OUTPUT
          else
            echo "lockfile=false" >> $GITHUB_OUTPUT
          fi
      - name: Install dependencies (with lockfile)
        if: steps.check_lockfile.outputs.lockfile == 'true'
        run: npm ci
      - name: Install dependencies (no lockfile, fallback)
        if: steps.check_lockfile.outputs.lockfile == 'false'
        run: npm install
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm test -- --ci --passWithNoTests

  codeql-scan:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build-and-test
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Check for package-lock.json
        id: check_lockfile
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo "lockfile=true" >> $GITHUB_OUTPUT
          else
            echo "lockfile=false" >> $GITHUB_OUTPUT
          fi
      - name: Install dependencies (with lockfile)
        if: steps.check_lockfile.outputs.lockfile == 'true'
        run: npm ci
      - name: Install dependencies (no lockfile, fallback)
        if: steps.check_lockfile.outputs.lockfile == 'false'
        run: npm install
      - name: Build for production
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
